export const USERS_URL = 'https://natural-wines-api.herokuapp.com/users'
export const USER_LOGOUT = 'https://natural-wines-api.herokuapp.com/users/logout'
export const SESSIONS_URL = 'https://natural-wines-api.herokuapp.com/sessions'
export const WINES_URL = 'https://natural-wines-api.herokuapp.com/wines'
export const PRODUCERS_URL = 'https://natural-wines-api.herokuapp.com/producers'